=== kvadro1/filedossier/filedossier-ddl/src/main/resources/schemas/filedossier/ddl.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns="urn:ru:ilb:filedossier:ddl"
    attributeFormDefault="unqualified"
    elementFormDefault="qualified"
    targetNamespace="urn:ru:ilb:filedossier:ddl"
>
    <xsd:element name="package" type="package"/>
    <xsd:complexType name="package">
        <xsd:annotation>
            <xsd:documentation>Пакет досье</xsd:documentation>
        </xsd:annotation>
        <xsd:sequence>
            <xsd:element name="code" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation>код пакета</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="name" type="xsd:string" >
                <xsd:annotation>
                    <xsd:documentation>Наименование пакета</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element ref="dossier" minOccurs="0" maxOccurs="unbounded">
                <xsd:annotation>
                    <xsd:documentation>Досье</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:element name="dossier" type="dossier"/>
    <xsd:complexType name="dossier">
        <xsd:annotation>
            <xsd:documentation>Модель досье</xsd:documentation>
        </xsd:annotation>
        <xsd:sequence>
            <xsd:element name="code" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation>код досье</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="name" type="xsd:string" >
                <xsd:annotation>
                    <xsd:documentation>Наименование досье</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element ref="dossierFile" minOccurs="0" maxOccurs="unbounded">
                <xsd:annotation>
                    <xsd:documentation>Файлы досье</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:element name="dossierFile" type="dossierFile"/>
    <xsd:complexType name="dossierFile">
        <xsd:annotation>
            <xsd:documentation>Модель файла досье</xsd:documentation>
        </xsd:annotation>

        <xsd:sequence>
            <xsd:element name="code" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation>Код файла</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="name" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation>Наименование</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="readonly" type="xsd:string"  minOccurs="0">
                <xsd:annotation>
                    <xsd:documentation>Только для чтения</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="required" type="xsd:string"  minOccurs="0">
                <xsd:annotation>
                    <xsd:documentation>Обязательный файл</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="hidden" type="xsd:string"  minOccurs="0">
                <xsd:annotation>
                    <xsd:documentation>Скрытый файл</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="mediaType" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation>Тип содержимого</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="representation" type="representation"  minOccurs="0" maxOccurs="unbounded">
                <xsd:annotation>
                    <xsd:documentation>Представления файла</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:element name="representation" type="representation"/>
    <xsd:complexType name="representation">
        <xsd:annotation>
            <xsd:documentation>Преставление файла досье</xsd:documentation>
        </xsd:annotation>
        <xsd:sequence>
            <xsd:element name="mediaType" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation>Тип содержимого</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="stylesheet" type="xsd:string" minOccurs="0">
                <xsd:annotation>
                    <xsd:documentation>Шаблон трансформации</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="template" type="xsd:string" minOccurs="0">
                <xsd:annotation>
                    <xsd:documentation>Шаблон файла (например для ods)</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="schema" type="xsd:string" minOccurs="0">
                <xsd:annotation>
                    <xsd:documentation>schema URL</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="meta" type="xsd:string" minOccurs="0">
                <xsd:annotation>
                    <xsd:documentation>meta URL</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="multipart" type="xsd:string" minOccurs="0">
                <xsd:annotation>
                    <xsd:documentation>Is representation in multiple files</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== kvadro1/filedossier/filedossier-core/src/test/resources/models/testmodel.xml
<?xml version="1.0" encoding="UTF-8"?>
<package
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="urn:ru:ilb:filedossier:ddl"
    xsi:schemaLocation="urn:ru:ilb:filedossier:ddl ../../../../../filedossier-ddl/src/main/resources/schemas/filedossier/ddl.xsd">
    <code>testmodel</code>
    <name>Тестовый пакет досье</name>
    <dossier>
        <code>TEST</code>
        <name>Тестовое досье</name>
        <dossierFile>
            <code>file1</code>
            <name>Файл 1</name>
            <readonly>false</readonly>
            <required>true</required>
            <hidden>false</hidden>
            <mediaType>application/xml</mediaType>
        </dossierFile>
        <dossierFile>
            <code>fairpricecalc</code>
            <name>Тест имя</name>
            <readonly>false</readonly>
            <required>true</required>
            <hidden>false</hidden>
            <mediaType>application/xml</mediaType>
            <representation>
                <mediaType>application/vnd.oasis.opendocument.spreadsheet</mediaType>
                <stylesheet>representations/fairpriceorder/content.xsl</stylesheet>
                <template>representations/fairpriceorder/template.ods</template>
                <schema></schema>
            </representation>
        </dossierFile>
<dossierFile>
            <code>jurnals</code>
            <name>Test name 1</name>
            <readonly>false</readonly>
            <required>true</required>
            <hidden>false</hidden>
            <mediaType>application/xml</mediaType>
            <representation>
                <mediaType>application/pdf</mediaType>
                <stylesheet>https://${ru.bystrobank.apps.meta.url}/schemas/doctemplates/jurnals/percentsheet.xsd</stylesheet>
                <template>representations/jurnals/content.xml</template>
                <schema>https://${ru.bystrobank.apps.meta.url}/stylesheets/doctemplates/jurnals/percentsheet.xsl</schema>
                <meta>https://${ru.bystrobank.apps.meta.url}/&amp;uid=doctree:11f462ebdb14a5673ff41a5c75c5176552fad343:</meta>
            </representation>
        </dossierFile>
    </dossier>
</package>

=== kvadro1/filedossier/filedossier-components/src/test/resources/models/testmodel/testmodel.xml
<?xml version="1.0" encoding="UTF-8"?>
<package
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="urn:ru:ilb:filedossier:ddl"
    xsi:schemaLocation="urn:ru:ilb:filedossier:ddl ../../../../../../filedossier-ddl/src/main/resources/schemas/filedossier/ddl.xsd">
    <code>testmodel</code>
    <name>Тестовый пакет досье</name>
    <dossier>
        <code>TEST</code>
        <name>Тестовое досье</name>
        <dossierFile>
            <code>file1</code>
            <name>Файл 1</name>
            <readonly>false</readonly>
            <required>true</required>
            <hidden>false</hidden>
            <variation>
                <mediaType>application/xml</mediaType>
            </variation>
        </dossierFile>
        <dossierFile>
            <code>fairpricecalc</code>
            <name>Тест имя</name>
            <readonly>false</readonly>
            <required>true</required>
            <hidden>false</hidden>
            <variation>
                <mediaType>application/xml</mediaType>
                <representation>
                    <mediaType>application/vnd.oasis.opendocument.spreadsheet</mediaType>
                    <stylesheet>representations/fairpriceorder/content.xsl</stylesheet>
                    <template>representations/fairpriceorder/template.ods</template>
                    <schema></schema>
                </representation>
            </variation>
        </dossierFile>
        <dossierFile>
            <code>jurnals</code>
            <name>Test name 1</name>
            <readonly>false</readonly>
            <required>true</required>
            <hidden>false</hidden>
            <variation>
                <mediaType>application/xml</mediaType>
                <representation>
                    <mediaType>application/pdf</mediaType>
                    <stylesheet>https://devel.net.ilb.ru/meta/schemas/doctemplates/jurnals/percentsheet.xsd</stylesheet>
                    <schema>https://devel.net.ilb.ru/meta/stylesheets/doctemplates/jurnals/percentsheet.xsl</schema>
                    <meta>https://devel.net.ilb.ru/meta/&amp;uid=doctree:11f462ebdb14a5673ff41a5c75c5176552fad343:</meta>
                </representation>
            </variation>
        </dossierFile>
    </dossier>
</package>

=== kvadro1/filedossier/filedossier-ddl/src/test/resources/models/testmodel/testmodel.xml
<?xml version="1.0" encoding="UTF-8"?>
<package
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="urn:ru:ilb:filedossier:ddl"
    xsi:schemaLocation="urn:ru:ilb:filedossier:ddl ../../../../main/resources/schemas/filedossier/ddl.xsd">
    <code>testmodel</code>
    <name>Тестовый пакет досье</name>
    <dossier>
        <code>TEST</code>
        <name>Тестовое досье</name>
        <dossierFile>
            <code>fairpricecalc</code>
            <name>Тест имя</name>
            <readonly>false</readonly>
            <required>true</required>
            <hidden>false</hidden>
            <mediaType>application/xml</mediaType>
            <representation>
                <mediaType>application/vnd.oasis.opendocument.spreadsheet</mediaType>
                <stylesheet>representations/fairpriceorder/content.xsl</stylesheet>
                <template>representations/fairpriceorder/template.ods</template>
                <schema></schema>
            </representation>
        </dossierFile>
        <dossierFile>
            <code>jurnals</code>
            <name>Test name 1</name>
            <readonly>false</readonly>
            <required>true</required>
            <hidden>false</hidden>
            <mediaType>application/xml</mediaType>
            <attribute>
                <code>number</code>
                <name>Номер документа</name>
            </attribute>
            <representation>
                <mediaType>application/pdf</mediaType>
                <stylesheet>${ru.bystrobank.apps.meta.url}/schemas/doctemplates/jurnals/percentsheet.xsd</stylesheet>
                <schema>${ru.bystrobank.apps.meta.url}/stylesheets/doctemplates/jurnals/percentsheet.xsl</schema>
                <meta>${ru.bystrobank.apps.meta.url}/&amp;uid=doctree:11f462ebdb14a5673ff41a5c75c5176552fad343:</meta>
                <multipart>true</multipart>
            </representation>
        </dossierFile>
    </dossier>
</package>

=== kvadro1/filedossier/filedossier-web/src/main/resources/models/testmodel/testmodel.xml
<?xml version="1.0" encoding="UTF-8"?>
<package
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="urn:ru:ilb:filedossier:ddl"
    xsi:schemaLocation="urn:ru:ilb:filedossier:ddl ../../../../../filedossier-ddl/src/main/resources/schemas/filedossier/ddl.xsd">
    <code>testmodel</code>
    <name>Тестовый пакет досье</name>
    <dossier>
        <code>TEST</code>
        <name>Тестовое досье</name>
        <dossierFile>
            <code>fairpricecalc</code>
            <name>fairpricecalc (.ods test)</name>
            <readonly>false</readonly>
            <required>true</required>
            <hidden>false</hidden>
            <variation>
                <mediaType>application/json</mediaType>
                <representation>
                    <mediaType>application/vnd.oasis.opendocument.spreadsheet</mediaType>
                    <stylesheet>representations/fairpriceorder/content.xsl</stylesheet>
                    <template>representations/fairpriceorder/template.ods</template>
            </representation>
            </variation>
        </dossierFile>
        <dossierFile>
            <code>pts</code>
            <name>Скан ПТС</name>
            <readonly>false</readonly>
            <required>true</required>
            <hidden>false</hidden>
            <variation>
                <mediaType>image/jpeg</mediaType>
            </variation>
            <variation>
                <mediaType>application/pdf</mediaType>
            </variation>
        </dossierFile>
        <dossierFile>
            <code>bailregistry</code>
            <name>reestr zalogov</name>
            <readonly>false</readonly>
            <required>true</required>
            <hidden>false</hidden>
            <variation>
                <mediaType>application/json</mediaType>
                <representation>
                    <mediaType>application/xml</mediaType>
                </representation>
            </variation>
        </dossierFile>
    </dossier>
</package>

=== kvadro1/filedossier/filedossier-web/src/main/resources/models/stockvaluation/stockvaluation.xml
<?xml version="1.0" encoding="UTF-8"?>
<package xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:ru:ilb:filedossier:ddl" xsi:schemaLocation="urn:ru:ilb:filedossier:ddl ../../../../../filedossier-ddl/src/main/resources/schemas/filedossier/ddl.xsd">
    <code>stockvaluation</code>
    <name>Оценка стоимости ценных бумаг</name>
    <dossier>
        <code>stockvaluation_fairpricecalc</code>
        <name>Расчет справедливой цены</name>
        <dossierFile>
            <code>fairpricecalc</code>
            <name>Распоряжение</name>
            <readonly>true</readonly>
            <mediaType>application/json</mediaType>
            <representation>
                <mediaType>application/vnd.oasis.opendocument.spreadsheet</mediaType>
                <stylesheet>representations/fairpriceorder/content.xsl</stylesheet>
                <template>representations/fairpriceorder/template.ods</template>
            </representation>
        </dossierFile>

    </dossier>
</package>

=== kvadro1/filedossier/filedossier-web/src/main/resources/models/bailverification/bailverification.xml
<?xml version="1.0" encoding="utf-8"?>
<package
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="urn:ru:ilb:filedossier:ddl"
  xsi:schemaLocation="urn:ru:ilb:filedossier:ddl ../../../../../filedossier-ddl/src/main/resources/schemas/filedossier/ddl.xsd">
  <code>bailverification</code>
  <name>Проверка залога</name>
  <dossier>
    <code>bailverification</code>
    <name>Проверка залога</name>
    <dossierFile>
      <code>pts</code>
      <name>Скан ПТС</name>
      <readonly>false</readonly>
      <required>true</required>
      <hidden>false</hidden>
      <variation>
        <mediaType>image/jpeg</mediaType>
      </variation>
    </dossierFile>
  </dossier>
</package>
